modLoader="javafml"
loaderVersion="[47,)"
license="All rights reserved"
issueTrackerURL="https://github.com/DerToaster98/MultiHitBoxLib/issues"

[[mods]]
modId="multihitboxlib"
version="${file.jarVersion}"
displayName="Multihitbox Library"
displayURL="https://www.curseforge.com/minecraft/mc-mods/multihitboxlib"
logoFile="logo.png"
credits="DerToaster"
description='''
Library for advanced multihitbox mobs. Can sync hitboxes to Geckolib/AzureLib bones
'''
[[dependencies.multihitboxlib]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.multihitboxlib]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.20.2)"
    ordering="NONE"
    side="BOTH"
[[dependencies.multihitboxlib]]
    modId="geckolib"
    mandatory=false
    versionRange="[4.2,)"
    ordering="BEFORE"
    side="BOTH"
[[dependencies.multihitboxlib]]
    modId="azurelib"
    mandatory=false
    versionRange="[1.0.18,)"
    ordering="BEFORE"
    side="BOTH"
